### ISSUE TITLE
Test certificate check box doesn't do anything

### ISSUE THREAD

**Issue by stormmedia** [Microsoft/vsts-rm-extensions#217]
It's impossible to deploy to a IIS server when the certificate is not trused.  The check box "Test certificate" that is supposed to skip the verification doesn't change anything.  Tried to add "-allowUntrusted" to the "Additional Arguments" field doesn't change anything either.  The deployment works fine when using visual studio once the certificate has been added to the trusted certificate

**Comment by mvvsubbu** [comment]
Test certificate option is for skipping CA check during WinRM to the target machine. Set a variable system.debug = true and share the task logs.

**Comment by thomasmktong** [comment]
I have the same issue. I took a look at the code and found that the "Additional Arguments" are not passed to `Run-RemoteDeployment` at all.

Ref: https://github.com/Microsoft/vsts-rm-extensions/blob/7d4384a6c775688a99812738837435f8fb4675f6/Extensions/IISWebAppDeploy/Src/Tasks/IISWebAppDeploy/DeployIISWebApp.ps1#L112

Task Logs:

```
2017-08-25T09:52:18.5607409Z ##[debug]Evaluating condition for step: 'Deploy IIS App: ABC.Web.Api'
2017-08-25T09:52:18.5607409Z ##[debug]Evaluating: succeeded()
2017-08-25T09:52:18.5607409Z ##[debug]Evaluating succeeded:
2017-08-25T09:52:18.5607409Z ##[debug]=> (Boolean) True
2017-08-25T09:52:18.5607409Z ##[debug]Expanded: True
2017-08-25T09:52:18.5607409Z ##[debug]Result: True
2017-08-25T09:52:18.5607409Z ##[section]Starting: Deploy IIS App: ABC.Web.Api
2017-08-25T09:52:18.5763662Z ==============================================================================
2017-08-25T09:52:18.5763662Z Task         : WinRM - IIS Web App Deployment
2017-08-25T09:52:18.5763662Z Description  : Connect via WinRM, to deploy Web project locally on IIS, using Web Deploy
2017-08-25T09:52:18.5763662Z Version      : 1.4.4
2017-08-25T09:52:18.5763662Z Author       : Microsoft Corporation
2017-08-25T09:52:18.5763662Z Help         : [More Information](http://aka.ms/IISWebDeploy)
2017-08-25T09:52:18.5763662Z ==============================================================================
2017-08-25T09:52:18.6232418Z Preparing task execution handler.
2017-08-25T09:52:19.6388790Z Executing the powershell script: C:\VSTS-Agent-2.104.0\_work\_tasks\IISWebAppDeploy_50acc50f-7d15-470b-83c1-578b3f3eeba2\1.4.4\Main.ps1
2017-08-25T09:52:19.6388790Z ##[debug]PowerShellHandler.Execute - AddCommand(C:\VSTS-Agent-2.104.0\_work\_tasks\IISWebAppDeploy_50acc50f-7d15-470b-83c1-578b3f3eeba2\1.4.4\Main.ps1)
2017-08-25T09:52:19.6388790Z ##[debug]PowerShellHandler.Execute - Add inputParameters
2017-08-25T09:52:19.6388790Z ##[debug]PowerShellHandler.Execute - AddParameter(machinesList=ABCDE-WEB-VM1:8172)
2017-08-25T09:52:19.6388790Z ##[debug]PowerShellHandler.Execute - AddParameter(AdminUserName=*****support)
2017-08-25T09:52:19.6388790Z ##[debug]PowerShellHandler.Execute - AddParameter(AdminPassword=************)
2017-08-25T09:52:19.6388790Z ##[debug]PowerShellHandler.Execute - AddParameter(WinRMProtocol=Https)
2017-08-25T09:52:19.6388790Z ##[debug]PowerShellHandler.Execute - AddParameter(TestCertificate=true)
2017-08-25T09:52:19.6388790Z ##[debug]PowerShellHandler.Execute - AddParameter(WebDeployPackage=C:\VSTS-Agent-2.104.0\_work\r37\a\BuildDeploymentPackageWebApiVM\WebApiDropDev\ABC.Web.Api.zip)
2017-08-25T09:52:19.6388790Z ##[debug]PowerShellHandler.Execute - AddParameter(WebDeployParamFile=)
2017-08-25T09:52:19.6388790Z ##[debug]PowerShellHandler.Execute - AddParameter(OverRideParams=)
2017-08-25T09:52:19.6388790Z ##[debug]PowerShellHandler.Execute - AddParameter(WebsiteName=API)
2017-08-25T09:52:19.6388790Z ##[debug]PowerShellHandler.Execute - AddParameter(RemoveAdditionalFiles=true)
2017-08-25T09:52:19.6388790Z ##[debug]PowerShellHandler.Execute - AddParameter(ExcludeFilesFromAppData=false)
2017-08-25T09:52:19.6388790Z ##[debug]PowerShellHandler.Execute - AddParameter(TakeAppOffline=true)
2017-08-25T09:52:19.6388790Z ##[debug]PowerShellHandler.Execute - AddParameter(AdditionalArguments=-verb:sync -disableLink:AppPoolExtension -disableLink:ContentExtension -disableLink:CertificateExtension -allowUntrusted -whatif)
2017-08-25T09:52:19.6388790Z ##[debug]PowerShellHandler.Execute - AddParameter(DeployInParallel=false)
2017-08-25T09:52:19.7170046Z ##[debug]PowerShellHandler.Execute - Invoke
2017-08-25T09:52:19.8107574Z ##[debug]Loading module from path 'C:\VSTS-Agent-2.104.0\_work\_tasks\IISWebAppDeploy_50acc50f-7d15-470b-83c1-578b3f3eeba2\1.4.4\DeploymentSDK\InvokeRemoteDeployment.ps1'.
2017-08-25T09:52:19.8107574Z ##[debug]Dot-sourcing the script file 'C:\VSTS-Agent-2.104.0\_work\_tasks\IISWebAppDeploy_50acc50f-7d15-470b-83c1-578b3f3eeba2\1.4.4\DeploymentSDK\InvokeRemoteDeployment.ps1'.
2017-08-25T09:52:19.8263814Z ##[debug]Entering script DeployIISWebApp.ps1
2017-08-25T09:52:19.8263814Z ##[debug]machinesList = ABCDE-WEB-VM1:8172
2017-08-25T09:52:19.8263814Z ##[debug]adminUserName = *****support
2017-08-25T09:52:19.8263814Z ##[debug]winrmProtocol  = Https
2017-08-25T09:52:19.8263814Z ##[debug]testCertificate = true
2017-08-25T09:52:19.8263814Z ##[debug]webDeployPackage = C:\VSTS-Agent-2.104.0\_work\r37\a\BuildDeploymentPackageWebApiVM\WebApiDropDev\ABC.Web.Api.zip
2017-08-25T09:52:19.8263814Z ##[debug]webDeployParamFile = 
2017-08-25T09:52:19.8263814Z ##[debug]overRideParams = 
2017-08-25T09:52:19.8263814Z ##[debug]websiteName = API
2017-08-25T09:52:19.8263814Z ##[debug]removeAdditionalFiles = true
2017-08-25T09:52:19.8263814Z ##[debug]excludeFilesFromAppData = false
2017-08-25T09:52:19.8263814Z ##[debug]takeAppOffline = true
2017-08-25T09:52:19.8263814Z ##[debug]additionalArguments = -verb:sync -disableLink:AppPoolExtension -disableLink:ContentExtension -disableLink:CertificateExtension -allowUntrusted -whatif
2017-08-25T09:52:19.8263814Z ##[debug]deployInParallel = false
2017-08-25T09:52:19.8420057Z ##[debug]Triming inputs for excess spaces, double quotes
2017-08-25T09:52:19.8732563Z ##[debug]Executing main function in MsDeployOnTargetMachines : Execute-Main -WebDeployPackage "C:\VSTS-Agent-2.104.0\_work\r37\a\BuildDeploymentPackageWebApiVM\WebApiDropDev\ABC.Web.Api.zip" -WebDeployParamFile "" -OverRideParams "" -WebsiteName "API" -RemoveAdditionalFiles true -ExcludeFilesFromAppData false -TakeAppOffline true -AdditionalArguments "-verb:sync -disableLink:AppPoolExtension -disableLink:ContentExtension -disableLink:CertificateExtension -allowUntrusted -whatif"
2017-08-25T09:52:19.8888816Z Starting deployment of IIS Web Deploy Package : C:\VSTS-Agent-2.104.0\_work\r37\a\BuildDeploymentPackageWebApiVM\WebApiDropDev\ABC.Web.Api.zip
2017-08-25T09:52:19.8888816Z 
2017-08-25T09:52:19.8888816Z 
2017-08-25T09:52:19.9045070Z ##[debug]Entered Invoke-RemoteDeployment function
2017-08-25T09:52:19.9045070Z ##[debug]machinesList = ABCDE-WEB-VM1:8172
2017-08-25T09:52:19.9045070Z ##[debug]adminUserName = *****support
2017-08-25T09:52:19.9045070Z ##[debug]protocol = Https
2017-08-25T09:52:19.9045070Z ##[debug]Creating credentials object for connecting to remote host
2017-08-25T09:52:19.9201316Z ##[debug]Tokenizing machine name and port, to create dictonary
2017-08-25T09:52:19.9513829Z ##[debug]Splitting machine name and port into tokens
2017-08-25T09:52:20.8576456Z ##[debug]Using skipCA = True
2017-08-25T09:52:20.8576456Z ##[debug]Using useHttp = False
2017-08-25T09:52:20.8576456Z Performing deployment in sequentially on all machines.
2017-08-25T09:52:20.8576456Z 
2017-08-25T09:52:20.8576456Z 
2017-08-25T09:52:20.8576456Z Deployment started for machine: ABCDE-WEB-VM1 with port 8172.
2017-08-25T09:52:20.8576456Z 
2017-08-25T09:52:20.8576456Z 
2017-08-25T09:52:20.8576456Z ##[debug]Running Invoke-PsOnRemote
2017-08-25T09:52:20.8576456Z ##[debug]machineName = ABCDE-WEB-VM1
2017-08-25T09:52:20.8576456Z ##[debug]winRmPort = 8172
2017-08-25T09:52:20.8576456Z ##[debug]useHttp = False
2017-08-25T09:52:20.8576456Z ##[debug]skipCA = True
2017-08-25T09:52:20.8576456Z ##[debug]Initiating deployment on ABCDE-WEB-VM1
2017-08-25T09:52:20.8576456Z ##[debug]Loading module from path 'C:\VSTS-Agent-2.104.0\_work\_tasks\IISWebAppDeploy_50acc50f-7d15-470b-83c1-578b3f3eeba2\1.4.4\DeploymentSDK\Microsoft.VisualStudio.Services.DevTestLabs.Definition.dll'.
2017-08-25T09:52:20.8576456Z ##[debug]Loading module from path 'C:\VSTS-Agent-2.104.0\_work\_tasks\IISWebAppDeploy_50acc50f-7d15-470b-83c1-578b3f3eeba2\1.4.4\DeploymentSDK\Microsoft.VisualStudio.Services.DevTestLabs.Deployment.dll'.
2017-08-25T09:52:20.8576456Z ##[debug]Loading modules from C:\VSTS-Agent-2.104.0\_work\_tasks\IISWebAppDeploy_50acc50f-7d15-470b-83c1-578b3f3eeba2\1.4.4\DeploymentSDK
2017-08-25T09:52:20.8576456Z Deployment status for machine ABCDE-WEB-VM1 : Failed
2017-08-25T09:52:20.8576456Z 
2017-08-25T09:52:20.8576456Z 
2017-08-25T09:52:20.8576456Z ##[debug]Processed: ##vso[task.logissue type=error;code={"Dtl_Sdk_Error":{"PowershellPort":8172,"Protocol":"Https","TestCertificate":true,"WinrmConnectionSucceeded":false,"Error":"Connecting to remote server ABCDE-WEB-VM1 failed with the following error message : The server certificate on the destination computer (ABCDE-WEB-VM1:8172) has the following errors:     \r\nThe SSL certificate contains a common name (CN) that does not match the hostname. For more information, see the about_Remote_Troubleshooting Help topic."}};]
2017-08-25T09:52:20.8576456Z 
2017-08-25T09:52:20.8576456Z 
2017-08-25T09:52:20.8576456Z ##[debug]
2017-08-25T09:52:20.8576456Z 
2017-08-25T09:52:20.8576456Z MachineName       : ABCDE-WEB-VM1
2017-08-25T09:52:20.8576456Z Status            : Failed
2017-08-25T09:52:20.8576456Z DeploymentLog     : Permission denied while trying to connect to the target 
2017-08-25T09:52:20.8576456Z                     machine ABCDE-WEB-VM1 on the port:8172 via power shell 
2017-08-25T09:52:20.8576456Z                     remoting. Please check the following link for 
2017-08-25T09:52:20.8576456Z                     instructions: https://go.microsoft.com/fwlink/?LinkID=39023
2017-08-25T09:52:20.8576456Z                     6System.Management.Automation.Remoting.PSRemotingTransportE
2017-08-25T09:52:20.8576456Z                     xception: Connecting to remote server ABCDE-WEB-VM1 failed 
2017-08-25T09:52:20.8576456Z                     with the following error message : The server certificate 
2017-08-25T09:52:20.8576456Z                     on the destination computer (ABCDE-WEB-VM1:8172) has the 
2017-08-25T09:52:20.8576456Z                     following errors:     
2017-08-25T09:52:20.8576456Z                     The SSL certificate contains a common name (CN) that does 
2017-08-25T09:52:20.8576456Z                     not match the hostname. For more information, see the 
2017-08-25T09:52:20.8576456Z                     about_Remote_Troubleshooting Help topic.
2017-08-25T09:52:20.8576456Z                        at System.Management.Automation.Runspaces.AsyncResult.En
2017-08-25T09:52:20.8576456Z                     dInvoke()
2017-08-25T09:52:20.8576456Z                        at System.Management.Automation.Runspaces.Internal.Runsp
2017-08-25T09:52:20.8576456Z                     acePoolInternal.EndOpen(IAsyncResult asyncResult)
2017-08-25T09:52:20.8576456Z                        at System.Management.Automation.RemoteRunspace.Open()
2017-08-25T09:52:20.8576456Z                        at Microsoft.VisualStudio.Services.DevTestLabs.Deploymen
2017-08-25T09:52:20.8576456Z                     t.Deployment.PowershellExecutor.GetOpenedRunspace()
2017-08-25T09:52:20.8576456Z                        at Microsoft.VisualStudio.Services.DevTestLabs.Deploymen
2017-08-25T09:52:20.8576456Z                     t.Deployment.PowershellExecutor.EstablishRemoteSession()
2017-08-25T09:52:20.8576456Z                        at Microsoft.VisualStudio.Services.DevTestLabs.Deploymen
2017-08-25T09:52:20.8576456Z                     t.RetryExecutor.Execute(Action action)
2017-08-25T09:52:20.8576456Z                        at System.Threading.Tasks.Task.Execute()
2017-08-25T09:52:20.8576456Z                     --- End of stack trace from previous location where 
2017-08-25T09:52:20.8576456Z                     exception was thrown ---
2017-08-25T09:52:20.8576456Z                        at System.Runtime.ExceptionServices.ExceptionDispatchInf
2017-08-25T09:52:20.8576456Z                     o.Throw()
2017-08-25T09:52:20.8576456Z                        at System.Runtime.CompilerServices.TaskAwaiter.HandleNon
2017-08-25T09:52:20.8576456Z                     SuccessAndDebuggerNotification(Task task)
2017-08-25T09:52:20.8576456Z                        at Microsoft.VisualStudio.Services.DevTestLabs.Deploymen
2017-08-25T09:52:20.8576456Z                     t.Deployment.PowershellExecutor.<Initialize>d__29.MoveNext(
2017-08-25T09:52:20.8576456Z                     )
2017-08-25T09:52:20.8576456Z                     --- End of stack trace from previous location where 
2017-08-25T09:52:20.8576456Z                     exception was thrown ---
2017-08-25T09:52:20.8576456Z                        at System.Runtime.ExceptionServices.ExceptionDispatchInf
2017-08-25T09:52:20.8576456Z                     o.Throw()
2017-08-25T09:52:20.8576456Z                        at System.Runtime.CompilerServices.TaskAwaiter.HandleNon
2017-08-25T09:52:20.8576456Z                     SuccessAndDebuggerNotification(Task task)
2017-08-25T09:52:20.8576456Z                        at Microsoft.VisualStudio.Services.DevTestLabs.Deploymen
2017-08-25T09:52:20.8576456Z                     t.Deployment.PowershellExecutor.<Initialize>d__23.MoveNext(
2017-08-25T09:52:20.8576456Z                     )
2017-08-25T09:52:20.8576456Z                     --- End of stack trace from previous location where 
2017-08-25T09:52:20.8576456Z                     exception was thrown ---
2017-08-25T09:52:20.8576456Z                        at System.Runtime.ExceptionServices.ExceptionDispatchInf
2017-08-25T09:52:20.8576456Z                     o.Throw()
2017-08-25T09:52:20.8576456Z                        at System.Runtime.CompilerServices.TaskAwaiter.HandleNon
2017-08-25T09:52:20.8576456Z                     SuccessAndDebuggerNotification(Task task)
2017-08-25T09:52:20.8576456Z                        at Microsoft.VisualStudio.Services.DevTestLabs.Deploymen
2017-08-25T09:52:20.8576456Z                     t.Deployment.RemoteDeploymentHelper.<Initialize>d__0.MoveNe
2017-08-25T09:52:20.8576456Z                     xt()
2017-08-25T09:52:20.8576456Z                     --- End of stack trace from previous location where 
2017-08-25T09:52:20.8576456Z                     exception was thrown ---
2017-08-25T09:52:20.8576456Z                        at System.Runtime.ExceptionServices.ExceptionDispatchInf
2017-08-25T09:52:20.8576456Z                     o.Throw()
2017-08-25T09:52:20.8576456Z                        at System.Runtime.CompilerServices.TaskAwaiter.HandleNon
2017-08-25T09:52:20.8576456Z                     SuccessAndDebuggerNotification(Task task)
2017-08-25T09:52:20.8576456Z                        at Microsoft.VisualStudio.Services.DevTestLabs.Deploymen
2017-08-25T09:52:20.8576456Z                     t.Deployment.DeploymentClient.<RunAsync>d__24.MoveNext()
2017-08-25T09:52:20.8576456Z ServiceLog        : 
2017-08-25T09:52:20.8576456Z Error             : System.Management.Automation.Remoting.PSRemotingTransportEx
2017-08-25T09:52:20.8576456Z                     ception: Connecting to remote server ABCDE-WEB-VM1 failed 
2017-08-25T09:52:20.8576456Z                     with the following error message : The server certificate 
2017-08-25T09:52:20.8576456Z                     on the destination computer (ABCDE-WEB-VM1:8172) has the 
2017-08-25T09:52:20.8576456Z                     following errors:     
2017-08-25T09:52:20.8576456Z                     The SSL certificate contains a common name (CN) that does 
2017-08-25T09:52:20.8576456Z                     not match the hostname. For more information, see the 
2017-08-25T09:52:20.8576456Z                     about_Remote_Troubleshooting Help topic.
2017-08-25T09:52:20.8576456Z                        at System.Management.Automation.Runspaces.AsyncResult.En
2017-08-25T09:52:20.8576456Z                     dInvoke()
2017-08-25T09:52:20.8576456Z                        at System.Management.Automation.Runspaces.Internal.Runsp
2017-08-25T09:52:20.8576456Z                     acePoolInternal.EndOpen(IAsyncResult asyncResult)
2017-08-25T09:52:20.8576456Z                        at System.Management.Automation.RemoteRunspace.Open()
2017-08-25T09:52:20.8576456Z                        at Microsoft.VisualStudio.Services.DevTestLabs.Deploymen
2017-08-25T09:52:20.8576456Z                     t.Deployment.PowershellExecutor.GetOpenedRunspace()
2017-08-25T09:52:20.8576456Z                        at Microsoft.VisualStudio.Services.DevTestLabs.Deploymen
2017-08-25T09:52:20.8576456Z                     t.Deployment.PowershellExecutor.EstablishRemoteSession()
2017-08-25T09:52:20.8576456Z                        at Microsoft.VisualStudio.Services.DevTestLabs.Deploymen
2017-08-25T09:52:20.8576456Z                     t.RetryExecutor.Execute(Action action)
2017-08-25T09:52:20.8576456Z                        at System.Threading.Tasks.Task.Execute()
2017-08-25T09:52:20.8576456Z                     --- End of stack trace from previous location where 
2017-08-25T09:52:20.8576456Z                     exception was thrown ---
2017-08-25T09:52:20.8576456Z                        at System.Runtime.ExceptionServices.ExceptionDispatchInf
2017-08-25T09:52:20.8576456Z                     o.Throw()
2017-08-25T09:52:20.8576456Z                        at System.Runtime.CompilerServices.TaskAwaiter.HandleNon
2017-08-25T09:52:20.8576456Z                     SuccessAndDebuggerNotification(Task task)
2017-08-25T09:52:20.8576456Z                        at Microsoft.VisualStudio.Services.DevTestLabs.Deploymen
2017-08-25T09:52:20.8576456Z                     t.Deployment.PowershellExecutor.<Initialize>d__29.MoveNext(
2017-08-25T09:52:20.8576456Z                     )
2017-08-25T09:52:20.8576456Z                     --- End of stack trace from previous location where 
2017-08-25T09:52:20.8576456Z                     exception was thrown ---
2017-08-25T09:52:20.8576456Z                        at System.Runtime.ExceptionServices.ExceptionDispatchInf
2017-08-25T09:52:20.8576456Z                     o.Throw()
2017-08-25T09:52:20.8576456Z                        at System.Runtime.CompilerServices.TaskAwaiter.HandleNon
2017-08-25T09:52:20.8576456Z                     SuccessAndDebuggerNotification(Task task)
2017-08-25T09:52:20.8576456Z                        at Microsoft.VisualStudio.Services.DevTestLabs.Deploymen
2017-08-25T09:52:20.8576456Z                     t.Deployment.PowershellExecutor.<Initialize>d__23.MoveNext(
2017-08-25T09:52:20.8576456Z                     )
2017-08-25T09:52:20.8576456Z                     --- End of stack trace from previous location where 
2017-08-25T09:52:20.8576456Z                     exception was thrown ---
2017-08-25T09:52:20.8576456Z                        at System.Runtime.ExceptionServices.ExceptionDispatchInf
2017-08-25T09:52:20.8576456Z                     o.Throw()
2017-08-25T09:52:20.8576456Z                        at System.Runtime.CompilerServices.TaskAwaiter.HandleNon
2017-08-25T09:52:20.8576456Z                     SuccessAndDebuggerNotification(Task task)
2017-08-25T09:52:20.8576456Z                        at Microsoft.VisualStudio.Services.DevTestLabs.Deploymen
2017-08-25T09:52:20.8576456Z                     t.Deployment.RemoteDeploymentHelper.<Initialize>d__0.MoveNe
2017-08-25T09:52:20.8576456Z                     xt()
2017-08-25T09:52:20.8576456Z                     --- End of stack trace from previous location where 
2017-08-25T09:52:20.8576456Z                     exception was thrown ---
2017-08-25T09:52:20.8576456Z                        at System.Runtime.ExceptionServices.ExceptionDispatchInf
2017-08-25T09:52:20.8576456Z                     o.Throw()
2017-08-25T09:52:20.8576456Z                        at System.Runtime.CompilerServices.TaskAwaiter.HandleNon
2017-08-25T09:52:20.8576456Z                     SuccessAndDebuggerNotification(Task task)
2017-08-25T09:52:20.8576456Z                        at Microsoft.VisualStudio.Services.DevTestLabs.Deploymen
2017-08-25T09:52:20.8576456Z                     t.Deployment.DeploymentClient.<RunAsync>d__24.MoveNext()
2017-08-25T09:52:20.8576456Z DeploymentSummary : {"PowershellPort":8172,"Protocol":"Https","TestCertificate"
2017-08-25T09:52:20.8576456Z                     :true,"WinrmConnectionSucceeded":false,"Error":"Connecting 
2017-08-25T09:52:20.8576456Z                     to remote server ABCDE-WEB-VM1 failed with the following 
2017-08-25T09:52:20.8576456Z                     error message : The server certificate on the destination 
2017-08-25T09:52:20.8576456Z                     computer (ABCDE-WEB-VM1:8172) has the following errors:    
2017-08-25T09:52:20.8576456Z                      \r\nThe SSL certificate contains a common name (CN) that 
2017-08-25T09:52:20.8576456Z                     does not match the hostname. For more information, see the 
2017-08-25T09:52:20.8576456Z                     about_Remote_Troubleshooting Help topic."}
2017-08-25T09:52:20.8576456Z 
2017-08-25T09:52:20.8576456Z 
2017-08-25T09:52:20.8576456Z 
2017-08-25T09:52:20.8576456Z 
2017-08-25T09:52:20.8576456Z ##[error]Microsoft.PowerShell.Commands.WriteErrorException: System.Management.Automation.Remoting.PSRemotingTransportException: Connecting to remote server ABCDE-WEB-VM1 failed with the following error message : The server certificate on the destination computer (ABCDE-WEB-VM1:8172) has the following errors:     
2017-08-25T09:52:20.8576456Z ##[debug]Processed: ##vso[task.logissue type=error;]Microsoft.PowerShell.Commands.WriteErrorException: System.Management.Automation.Remoting.PSRemotingTransportException: Connecting to remote server ABCDE-WEB-VM1 failed with the following error message : The server certificate on the destination computer (ABCDE-WEB-VM1:8172) has the following errors:     
2017-08-25T09:52:20.8576456Z The SSL certificate contains a common name (CN) that does not match the hostname. For more information, see the about_Remote_Troubleshooting Help topic.
2017-08-25T09:52:20.8576456Z    at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
2017-08-25T09:52:20.8576456Z    at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.EndOpen(IAsyncResult asyncResult)
2017-08-25T09:52:20.8576456Z    at System.Management.Automation.RemoteRunspace.Open()
2017-08-25T09:52:20.8576456Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.GetOpenedRunspace()
2017-08-25T09:52:20.8576456Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.EstablishRemoteSession()
2017-08-25T09:52:20.8576456Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.RetryExecutor.Execute(Action action)
2017-08-25T09:52:20.8576456Z    at System.Threading.Tasks.Task.Execute()
2017-08-25T09:52:20.8576456Z --- End of stack trace from previous location where exception was thrown ---
2017-08-25T09:52:20.8576456Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-08-25T09:52:20.8576456Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-08-25T09:52:20.8576456Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.<Initialize>d__29.MoveNext()
2017-08-25T09:52:20.8576456Z --- End of stack trace from previous location where exception was thrown ---
2017-08-25T09:52:20.8576456Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-08-25T09:52:20.8576456Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-08-25T09:52:20.8576456Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.<Initialize>d__23.MoveNext()
2017-08-25T09:52:20.8576456Z --- End of stack trace from previous location where exception was thrown ---
2017-08-25T09:52:20.8576456Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-08-25T09:52:20.8576456Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-08-25T09:52:20.8576456Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.RemoteDeploymentHelper.<Initialize>d__0.MoveNext()
2017-08-25T09:52:20.8576456Z --- End of stack trace from previous location where exception was thrown ---
2017-08-25T09:52:20.8576456Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-08-25T09:52:20.8576456Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2017-08-25T09:52:20.8576456Z    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.DeploymentClient.<RunAsync>d__24.MoveNext()
2017-08-25T09:52:20.8576456Z For more info please refer to http://aka.ms/iisextnreadme
2017-08-25T09:52:20.8732686Z ##[error]PowerShell script completed with 1 errors.
2017-08-25T09:52:20.8888946Z ##[section]Finishing: Deploy IIS App: ABC.Web.Api
```

**Comment by gerhardkoepfle** [comment]
still having same issue here

**Comment by niadak** [comment]
With Test Certificate option we only skip CA check validation, the task is failing with CN check validation. You need to add the host name in the trusted source in the SSL certificate.

You can try out Deployment Group feature which is pull based deployment model. We can remove the winrm dependency in this approch. You can configure agent on the target Machine and use IIS Web Deploy task to deploy the website. Please refer to the below docs for more details.

https://www.youtube.com/watch?v=535HmFjzrmg
https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/release/deployment-groups/
https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/release/deployment-groups/howto-provision-deployment-group-agents
https://blogs.msdn.microsoft.com/devops/2017/05/11/announcing-public-preview-of-the-new-deployment-groups-in-release-management/


Let us know if this helps.

**Comment by niadak** [comment]
@gerhardkoepfle , I am closing the issue. Please feel free to re-open if you need any help on this.
