### ISSUE TITLE
Download External TFS Artifact Task ignores web proxy configuration

### ISSUE THREAD

**Issue by alatas** [Microsoft/vsts-rm-extensions#289]
We have two different vsts/tfs instances. The source and the build job are placed on the VSTS instance (outside prem), release definition and release agent are placed on the on-prem TFS. The build and artifact upload jobs running without any problem. (I downloaded and checked artifacts from VSTS manually)

On release definition, I linked the artifacts with External TFS option. When I tried to release on-prem server with release job, the agents waits for about 90 sec and then thrown an exception. I checked the network connection while this attempt, It seems agents or task ignores the proxy configuration of the agent and tries to connect external tfs endpoint directly. 

ms-vscs-rm.vss-services-externaltfs version is 15.106.2

LOGS:

2017-10-16T12:59:02.5139516Z ##[section]Starting: Release
2017-10-16T12:59:02.5150118Z Current agent version: '2.123.0'
2017-10-16T12:59:02.5150118Z Agent is running behind proxy server: 'http://10.222.57.53:8080'
2017-10-16T12:59:03.0859621Z ##[section]Starting: Initialize Job
2017-10-16T12:59:03.0899540Z Prepare release directory.
2017-10-16T12:59:03.0919924Z ReleaseId=73, TeamProjectId=2a38a52e-9612-48ff-90de-b86c80981639, ReleaseDefinitionName=XXXX
2017-10-16T12:59:03.1010005Z Release folder: C:\Agent\_work\r1\a
...
				[AGENT_PROXYURL] --> [http://10.222.57.53:8080]
...
				[AGENT_VERSION] --> [2.123.0]
...
				[BUILD_BUILDID] --> [8]
				[BUILD_BUILDNUMBER] --> [8]
				[BUILD_DEFINITIONNAME] --> [YYYYY Build]
				[BUILD_DEFINTIONID] --> [1]
				[BUILD_TYPE] --> [ExternalTfsBuild]
...
				[RELEASE_ARTIFACTS_YYYYY_BUILD_BUILDID] --> [8]
				[RELEASE_ARTIFACTS_YYYYY_BUILD_BUILDNUMBER] --> [8]
				[RELEASE_ARTIFACTS_YYYYY_BUILD_DEFINITIONNAME] --> [YYYYY Build]
				[RELEASE_ARTIFACTS_YYYYY_BUILD_DEFINTIONID] --> [1]
				[RELEASE_ARTIFACTS_YYYYY_BUILD_TYPE] --> [ExternalTfsBuild]
...
2017-10-16T12:59:03.1389537Z Download all required tasks.
2017-10-16T12:59:03.2170045Z ##[section]Finishing: Initialize Job
2017-10-16T12:59:03.2659765Z ##[section]Starting: Download Artifacts
2017-10-16T12:59:03.4729459Z Downloading artifact
2017-10-16T12:59:03.4839874Z Creating artifacts directory: C:\Agent\_work\r1\a
2017-10-16T12:59:03.4989446Z Created artifacts directory: C:\Agent\_work\r1\a
2017-10-16T12:59:03.5019451Z Starting artifacts download...
2017-10-16T12:59:03.5270058Z Downloading linked artifact YYYYY Build of type Custom...
2017-10-16T12:59:03.5329456Z Ensuring artifact folder C:\Agent\_work\r1\a\YYYYY Build exists and is clean.
2017-10-16T12:59:45.8377015Z An error occurred during download: System.AggregateException: One or more errors occurred. (An error occurred while sending the request. The operation timed out) ---> System.Net.WebException: An error occurred while sending the request. The operation timed out ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The operation timed out
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.HttpWebRequest.<SendRequest>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.TeamFoundation.DistributedTask.Common.ServiceEndpoints.EndpointProxy.ExecuteRequest(String endpointUrl, String resourceUrl, ResponseSelector selector, IEndpointAuthorizer authorizer)
   at Microsoft.TeamFoundation.DistributedTask.Common.ServiceEndpoints.EndpointProxy.QueryEndpoint(ServiceEndpoint serviceEndpoint, String endpointUrl, String resourceUrl, String resultSelector, String resultTemplate, List`1 authorizationHeaders, Dictionary`2 parameters)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.Artifacts.CustomArtifact.EnsureVersionBelongsToLinkedDefinition(ArtifactDefinition artifactDefinition)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.Artifacts.CustomArtifact.<DownloadAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseJobExtension.<>c__DisplayClass34_2.<<DownloadArtifacts>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.RetryExecutor.<ExecuteAsync>d__20.MoveNext()
---> (Inner Exception #0) System.Net.WebException: An error occurred while sending the request. The operation timed out ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The operation timed out
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.HttpWebRequest.<SendRequest>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---

2017-10-16T12:59:45.8387225Z Retrying download...

**Comment by GitHubSriramB** [comment]
@alatas - thanks for the feedback. We plan to enable downloading External TFS Build artifacts using task in next couple of weeks. We have handled honoring proxy on the agent machine in the download task implementation. We will be updating the External TFS extension to include the task prior to enabling the feature to use task for the download.

Will inform you once this feature is enabled.

**Comment by alatas** [comment]
Thanks for your response, I willing to help if you want a beta tester :smile:

In addition, It might be better If artifact download could happen over the on-prem tfs server. Because the servers and release agents usually don't have internet access in enterprise environments. First on-prem TFS server downloads the External TFS Artifact, and then on-prem release agents download the artifacts from TFS server.

**Comment by GitHubSriramB** [comment]
@alatas - we have updated External TFS artifact extension in marketplace. It will now use task to download the artifact.

Could you pl. try your scenario & let us know if it works?

**Comment by alatas** [comment]
@GitHubSriramB 
I tested today with latest version (15.145.0) and it didn't worked. When I tried to debug the release, I saw the proxy configuration. 

Then I tried to change download.js for giving the proxy configuration manually, but it didn't worked either.

``` javascript
var option = { proxy: { proxyUrl: "http://proxyserver:8080" }, ignoreSslError: true };
var vssConnection = new WebApi_1.WebApi(endpointUrl, credentialHandler, option);
```

```
2019-02-15T11:54:59.9755911Z ##[section]Starting: Download Artifacts - External Build
2019-02-15T11:55:00.0228300Z ==============================================================================
2019-02-15T11:55:00.0228529Z Task         : Download Artifacts - External Build
2019-02-15T11:55:00.0228639Z Description  : Download artifacts from VSTS\TFS build
2019-02-15T11:55:00.0228761Z Version      : 15.145.0
2019-02-15T11:55:00.0228857Z Author       : ms-vscs-rm
2019-02-15T11:55:00.0228950Z Help         : 
2019-02-15T11:55:00.0229057Z ==============================================================================
2019-02-15T11:55:00.4648307Z ##[debug]agent.TempDirectory=C:\Agent\_work\_temp
2019-02-15T11:55:00.4652224Z ##[debug]loading inputs and endpoints
2019-02-15T11:55:00.4652499Z ##[debug]loading ENDPOINT_AUTH_94bc5d94-0610-46c4-8250-7552dee7e086
2019-02-15T11:55:00.4652911Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_94bc5d94-0610-46c4-8250-7552dee7e086_APITOKEN
2019-02-15T11:55:00.4653189Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2019-02-15T11:55:00.4653531Z ##[debug]loading ENDPOINT_AUTH_SCHEME_94bc5d94-0610-46c4-8250-7552dee7e086
2019-02-15T11:55:00.4654634Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2019-02-15T11:55:00.4655904Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2019-02-15T11:55:00.4656190Z ##[debug]loading INPUT_CONNECTION
2019-02-15T11:55:00.4656611Z ##[debug]loading INPUT_DEFINITION
2019-02-15T11:55:00.4657700Z ##[debug]loading INPUT_DOWNLOADPATH
2019-02-15T11:55:00.4658110Z ##[debug]loading INPUT_ITEMPATTERN
2019-02-15T11:55:00.4658493Z ##[debug]loading INPUT_PROJECT
2019-02-15T11:55:00.4658713Z ##[debug]loading INPUT_VERSION
2019-02-15T11:55:00.4658891Z ##[debug]loaded 12
2019-02-15T11:55:00.4659241Z ##[debug]Agent.ProxyUrl=http://proxyserver:8080
2019-02-15T11:55:00.4661097Z ##[debug]Agent.ProxyUsername=undefined
2019-02-15T11:55:00.4661694Z ##[debug]Agent.ProxyPassword=undefined
2019-02-15T11:55:00.4661891Z ##[debug]Agent.ProxyBypassList=["xxx.com"]
2019-02-15T11:55:00.4662058Z ##[debug]expose agent proxy configuration.
2019-02-15T11:55:00.4662232Z ##[debug]Agent.CAInfo=undefined
2019-02-15T11:55:00.4662392Z ##[debug]Agent.ClientCert=undefined
2019-02-15T11:55:00.4662562Z ##[debug]Agent.SkipCertValidation=undefined
2019-02-15T11:55:00.7107978Z ##[debug]check path : C:\Agent\_work\_tasks\DownloadExternalBuildArtifacts_b099689b-039e-4450-8658-c72e3895dd3f\15.145.0\node_modules\artifact-engine\lib.json
2019-02-15T11:55:00.7110701Z ##[debug]adding resource file: C:\Agent\_work\_tasks\DownloadExternalBuildArtifacts_b099689b-039e-4450-8658-c72e3895dd3f\15.145.0\node_modules\artifact-engine\lib.json
2019-02-15T11:55:00.7111542Z ##[debug]system.culture=en-US
2019-02-15T11:55:00.9121579Z ##[debug]check path : C:\Agent\_work\_tasks\DownloadExternalBuildArtifacts_b099689b-039e-4450-8658-c72e3895dd3f\15.145.0\task.json
2019-02-15T11:55:00.9122110Z ##[debug]adding resource file: C:\Agent\_work\_tasks\DownloadExternalBuildArtifacts_b099689b-039e-4450-8658-c72e3895dd3f\15.145.0\task.json
2019-02-15T11:55:00.9122388Z ##[debug]system.culture=en-US
2019-02-15T11:55:00.9213581Z ##[debug]connection=94bc5d94-0610-46c4-8250-7552dee7e086
2019-02-15T11:55:00.9218462Z ##[debug]project=6d6af4f7-48e3-45c2-8484-b1a8b9f33872
2019-02-15T11:55:00.9221051Z ##[debug]definition=2
2019-02-15T11:55:00.9224163Z ##[debug]version=6
2019-02-15T11:55:00.9227376Z ##[debug]itemPattern=**
2019-02-15T11:55:00.9229883Z ##[debug]downloadPath=C:\Agent\_work\r3\a
2019-02-15T11:55:00.9231925Z ##[debug]94bc5d94-0610-46c4-8250-7552dee7e086=https://XXX.visualstudio.com/
2019-02-15T11:55:00.9234844Z ##[debug]94bc5d94-0610-46c4-8250-7552dee7e086 auth param username = null
2019-02-15T11:55:00.9240862Z ##[debug]94bc5d94-0610-46c4-8250-7552dee7e086 auth param apitoken = ***
2019-02-15T11:55:00.9244661Z ##[debug]System.Debug=True
2019-02-15T11:55:00.9245260Z ##[debug]release.artifact.download.parallellimit=undefined
2019-02-15T11:55:22.0902295Z ##[warning]Can\'t find loc string for key: RetryingOperation
2019-02-15T11:55:22.0916917Z ##[debug]Processed: ##vso[task.issue type=warning;]Can\'t find loc string for key: RetryingOperation
2019-02-15T11:55:22.0917464Z RetryingOperation getArtifacts 3
2019-02-15T11:55:22.0928049Z { Error: connect ETIMEDOUT 13.107.6.175:443
2019-02-15T11:55:22.0928666Z     at Object.exports._errnoException (util.js:1018:11)
2019-02-15T11:55:22.0929218Z     at exports._exceptionWithHostPort (util.js:1041:20)
2019-02-15T11:55:22.0929680Z     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)
2019-02-15T11:55:22.0929864Z   code: 'ETIMEDOUT',
2019-02-15T11:55:22.0930029Z   errno: 'ETIMEDOUT',
2019-02-15T11:55:22.0930166Z   syscall: 'connect',
2019-02-15T11:55:22.0930293Z   address: '13.107.6.175',
2019-02-15T11:55:22.0930412Z   port: 443,
2019-02-15T11:55:22.0930527Z   statusCode: undefined }
2019-02-15T11:55:22.0930862Z ##[debug]Error: connect ETIMEDOUT 13.107.6.175:443
```
