### ISSUE TITLE
Downloading artifacts using artifact engine failing inside windows container

### ISSUE THREAD

**Issue by omeshp** [Microsoft/vsts-rm-extensions#296]
Failure trace:
2017-10-31T07:46:10.3186195Z ##[section]Starting: Download artifact - UCM-Private-vNext-Build
2017-10-31T07:46:10.3432362Z ==============================================================================
2017-10-31T07:46:10.3432362Z Task         : Download Build Artifacts
2017-10-31T07:46:10.3432362Z Description  : Download Build Artifacts
2017-10-31T07:46:10.3432362Z Version      : 0.1.58
2017-10-31T07:46:10.3432362Z Author       : Microsoft Corporation
2017-10-31T07:46:10.3432362Z Help         : 
2017-10-31T07:46:10.3432362Z ==============================================================================
2017-10-31T07:46:10.7276060Z fs.js:994
2017-10-31T07:46:10.7276060Z   binding.lstat(pathModule._makeLong(path), statValues);
2017-10-31T07:46:10.7276060Z           ^
2017-10-31T07:46:10.7276060Z 
2017-10-31T07:46:10.7276060Z Error: ENOENT: no such file or directory, lstat 'C:\ContainerMappedDirectories'
2017-10-31T07:46:10.7276060Z     at Error (native)
2017-10-31T07:46:10.7276060Z     at Object.fs.lstatSync (fs.js:994:11)
2017-10-31T07:46:10.7276060Z     at Object.realpathSync (fs.js:1676:21)
2017-10-31T07:46:10.7276060Z     at toRealPath (module.js:133:13)
2017-10-31T07:46:10.7276060Z     at Function.Module._findPath (module.js:181:22)
2017-10-31T07:46:10.7276060Z     at Function.Module._resolveFilename (module.js:467:25)
2017-10-31T07:46:10.7276060Z     at Function.Module._load (module.js:417:25)
2017-10-31T07:46:10.7276060Z     at Module.runMain (module.js:604:10)
2017-10-31T07:46:10.7276060Z     at run (bootstrap_node.js:390:7)
2017-10-31T07:46:10.7276060Z     at startup (bootstrap_node.js:150:9)
2017-10-31T07:46:10.8232109Z ##[error]Exit code 1 returned from process: file name 'C:\Agent\externals\node\bin\node.exe', arguments '"C:\Agent\_work\28EF2D30F0CA\_tasks\DownloadBuildArtifacts_a433f589-fce1-4460-9ee6-44a624aeb1fb\0.1.58\main.js"'.
2017-10-31T07:46:10.8242118Z ##[section]Finishing: Download artifact - UCM-Private-vNext-Build

Relevant node issue:
https://github.com/nodejs/node/issues/8897

**Comment by omeshp** [comment]
This is a windows container node specific issue which should be fixed by windows team.
