### ISSUE TITLE
Jenkin as CI and TFS for CD throwing Error: Microsoft.PowerShell.Commands.WriteErrorException 

### ISSUE THREAD

**Issue by jigneshc** [Microsoft/vsts-rm-extensions#367]
I am doing CI in Jenkins and whatever will be the output I am trying to deploy it from TFS. The task include in my release are:
1. Copy Files
2. Manage IIS App

While doing this I am getting following error:

 **##[error]Microsoft.PowerShell.Commands.WriteErrorException: Deployment on one or more machines failed. System.**Management.Automation.Remoting.PSRemotingTransportException: Connecting to remote server ********.************.com failed with the following error message : The WinRM client sent a request to an HTTP server and got a response saying the requested HTTP URL was not available. This is usually returned by a HTTP server that does not support the WS-Management protocol. For more information, see the about_Remote_Troubleshooting Help topic.

    at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()

    at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.EndOpen(IAsyncResult asyncResult)

   at System.Management.Automation.RemoteRunspace.Open()

   at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.GetOpenedRunspace()

    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.EstablishRemoteSession()

   at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.RetryExecutor.Execute(Action action)

    at System.Threading.Tasks.Task.Execute()

 --- End of stack trace from previous location where exception was thrown ---

    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.<Initialize>d__29.MoveNext()

 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.<Initialize>d__23.MoveNext()

 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.RemoteDeploymentHelper.<Initialize>d__0.MoveNext()

 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

    at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.DeploymentClient.<RunAsync>d__24.MoveNext()

 For more info please refer to http://aka.ms/iisextnreadme
 **##[error]PowerShell script completed with 1 errors.**
 ##[section]Finishing: Deploy IIS App: **"Directory of build drop"**
 ##[section]Finishing: Release

**Comment by pavanadepu2** [comment]
@jigneshc, it seems WinRM is not configured on the target machine on which you are deploying the IIS application. Configure the WinRM on the target machine by running [this](https://github.com/Microsoft/vsts-rm-extensions/blob/master/TaskModules/powershell/WinRM/WinRM-Http-Https/ConfigureWinRM.ps1) PowerShell script.

Retry the deployment once the WinRM is successfully configured. Please let us know if you still see an issue.

**Comment by jigneshc** [comment]
@pavanadepu2 , WinRM is already installed on target machine, still I am not able to deploy.

ERROR:

**Microsoft.PowerShell.Commands.WriteErrorException: Deployment on one or more machines failed. System.Management.Automation.Remoting.PSRemotingTransportException: Connecting to remote server ******.***.com failed with the following error message : Access is denied. For more information, see the about_Remote_Troubleshooting Help topic**

I think above issue is indicating issue related to permission, what you think?

**Comment by pavanadepu2** [comment]
Yes, this issue is related to permission and is different from the error reported initially. I need to debug the issue on the target machine. Please email your convenient time to RM_Customer_Queries@microsoft.com to debug the issue further.
