### ISSUE TITLE
IISWebAppDeploy ERROR_FILE_IN_USE

### ISSUE THREAD

**Issue by AHoran** [Microsoft/vsts-rm-extensions#49]
Using TFS 2015 Update 2.
IISWebAppMgmt: 1.0.2
IISWebAppDeploy: 1.0.1

In my release I have a Manage IIS App task followed by a Deploy IIS App task. If I add _"Additional AppCmd.exe Commands"_ to the Manage IIS task, then I (almost) always receive the following error when trying to deploy my package:
**Deployment failed on machine xx.yy.com with following message : System.Exception: Error Code: ERROR_FILE_IN_USE**
As soon as I remove the additional commands then the problem goes away.

The additional commands are:
```
set apppool "poolname" /enable32BitAppOnWin64:true
set apppool "poolname" /autoStart:true
set apppool "poolname" /processModel.idleTimeout:02:00:00
```

**Comment by AHoran** [comment]
Actually now I'm getting it even without the additional appcmd items.

How do I find out which file is causing this and why?

**Comment by mvvsubbu** [comment]
Can you set system.debug variable to true and then try the release or build. Please attach the logs for the release or build here.

**Comment by AHoran** [comment]
> 2016-06-16T04:42:11.2839477Z Executing the powershell script: D:\agent2\tasks\IISWebAppDeploy\1.0.1\Main.ps1
2016-06-16T04:42:11.4243513Z ##[debug]Loading module from path 'D:\agent2\tasks\IISWebAppDeploy\1.0.1\DeploymentSDK\InvokeRemoteDeployment.ps1'.
2016-06-16T04:42:11.4399517Z ##[debug]Dot-sourcing the script file 'D:\agent2\tasks\IISWebAppDeploy\1.0.1\DeploymentSDK\InvokeRemoteDeployment.ps1'.
2016-06-16T04:42:11.4399517Z ##[debug]Entering script DeployIISWebApp.ps1
2016-06-16T04:42:11.4555521Z ##[debug]machinesList = projectname-dev.myazureregion.cloudapp.azure.com
2016-06-16T04:42:11.4555521Z ##[debug]adminUserName = anAdminUser
2016-06-16T04:42:11.4555521Z ##[debug]winrmProtocol  = Https
2016-06-16T04:42:11.4555521Z ##[debug]testCertificate = true
2016-06-16T04:42:11.4555521Z ##[debug]webDeployPackage = C:\projectname\Publish\WebsiteName.WEB.zip
2016-06-16T04:42:11.4555521Z ##[debug]webDeployParamFile = 
2016-06-16T04:42:11.4555521Z ##[debug]overRideParams = 
2016-06-16T04:42:11.4555521Z ##[debug]websiteName = projectnameWeb
2016-06-16T04:42:11.4555521Z ##[debug]deployInParallel = true
2016-06-16T04:42:11.4555521Z ##[debug]Triming inputs for excess spaces, double quotes
2016-06-16T04:42:11.4711525Z ##[debug]Computing override params for msdeploy.
2016-06-16T04:42:11.4711525Z ##[debug]Adding override params to ensure deployment happens on projectnameWeb
2016-06-16T04:42:11.5023533Z ##[debug]Executing main funnction in MsDeployOnTargetMachines : Execute-Main -WebDeployPackage "C:\projectname\Publish\WebsiteName.WEB.zip" -WebDeployParamFile "" -OverRideParams "name=`"IIS Web Application Name`",value=`"projectnameWeb`""
2016-06-16T04:42:11.5179537Z Starting deployment of IIS Web Deploy Package : C:\projectname\Publish\WebsiteName.WEB.zip
2016-06-16T04:42:11.5491545Z ##[debug]Entered Invoke-RemoteDeployment function
2016-06-16T04:42:11.5491545Z ##[debug]machinesList = projectname-dev.myazureregion.cloudapp.azure.com
2016-06-16T04:42:11.5491545Z ##[debug]adminUserName = anAdminUser
2016-06-16T04:42:11.5491545Z ##[debug]protocol = Https
2016-06-16T04:42:11.5491545Z ##[debug]Creating credentials object for connecting to remote host
2016-06-16T04:42:11.5647549Z ##[debug]Tokenizing machine name and port, to create dictonary
2016-06-16T04:42:11.5647549Z ##[debug]Splitting machine name and port into tokens
2016-06-16T04:42:11.5803553Z ##[debug]Using skipCA = True
2016-06-16T04:42:11.5803553Z ##[debug]Using useHttp = False
2016-06-16T04:42:11.5803553Z Performing deployment in parallel on all the machines.
2016-06-16T04:42:11.5803553Z Deployment started for machine: projectname-dev.myazureregion.cloudapp.azure.com with port 5986.
2016-06-16T04:42:11.7207589Z ##[debug]Exporting function 'New-PSWorkflowSession'.
2016-06-16T04:42:11.7207589Z ##[debug]Exporting alias 'nwsn'.
2016-06-16T04:42:42.1571393Z Deployment status for machine projectname-dev.myazureregion.cloudapp.azure.com :
2016-06-16T04:42:42.1571393Z  
2016-06-16T04:42:42.1571393Z Failed
2016-06-16T04:42:42.1571393Z ##[debug]
2016-06-16T04:42:42.1571393Z 	 Deployment started on target machine...
2016-06-16T04:42:42.1571393Z System.AggregateException: Failed to execute the powershell script. Consult the logs below for details of the error.
2016-06-16T04:42:42.1571393Z Error Code: ERROR_FILE_IN_USE
2016-06-16T04:42:42.1571393Z  +At line:19 char:19
2016-06-16T04:42:42.1571393Z +         $result = cmd.exe /c "$command"
2016-06-16T04:42:42.1571393Z +                   ~~~~~~~~~~~~~~~~~~~~~
2016-06-16T04:42:42.1571393Z  CategoryInfo :NotSpecified: (Error Code: ERROR_FILE_IN_USE:String) [], RemoteException
2016-06-16T04:42:42.1571393Z  FullyQualifiedErrorId :NativeCommandError
2016-06-16T04:42:42.1571393Z **More Information: The file 'Antlr3.Runtime.dll' is in use.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_FILE_IN_USE.
2016-06-16T04:42:42.1571393Z  +At line:19 char:19
2016-06-16T04:42:42.1571393Z +         $result = cmd.exe /c "$command"**
2016-06-16T04:42:42.1571393Z +                   ~~~~~~~~~~~~~~~~~~~~~
2016-06-16T04:42:42.1571393Z  CategoryInfo :NotSpecified: (:) [], RemoteException
2016-06-16T04:42:42.1571393Z  FullyQualifiedErrorId :NativeCommandErrorMessage
2016-06-16T04:42:42.1571393Z Error count: 1.
2016-06-16T04:42:42.1571393Z  +At line:19 char:19
2016-06-16T04:42:42.1571393Z +         $result = cmd.exe /c "$command"
2016-06-16T04:42:42.1571393Z +                   ~~~~~~~~~~~~~~~~~~~~~
2016-06-16T04:42:42.1571393Z  CategoryInfo :NotSpecified: (:) [], RemoteException
2016-06-16T04:42:42.1571393Z  FullyQualifiedErrorId :NativeCommandErrorMessage
2016-06-16T04:42:42.1571393Z Info: Updating file (projectnameWeb\bin\Antlr3.Runtime.dll). ---> System.Management.Automation.RemoteException: Error Code: ERROR_FILE_IN_USE
2016-06-16T04:42:42.1571393Z    --- End of inner exception stack trace ---
2016-06-16T04:42:42.1571393Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.Invoke(String errorContextMessage, Boolean writeResultToLog, Boolean isCancellable, ActionPreference errorActionPreference)
2016-06-16T04:42:42.1571393Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.ScriptExecutor.ExecuteScript(IPowerShell powerShell, String script, String arguments, Boolean isScriptDotSourced, Boolean useHttp)
2016-06-16T04:42:42.1571393Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.DeploymentService.RunPowerShellScripts(DeploymentMachineSpecification deploymentMachine, ScriptSpecification scriptSpecification, ScriptSpecification initializationScriptSpecification, String applicationPath, IPowerShell powerShellSession)
2016-06-16T04:42:42.1571393Z ---> (Inner Exception #0) System.Management.Automation.RemoteException: Error Code: ERROR_FILE_IN_USE<---
2016-06-16T04:42:42.1571393Z ---> (Inner Exception #1) System.Management.Automation.RemoteException: More Information: The file 'Antlr3.Runtime.dll' is in use.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_FILE_IN_USE.
2016-06-16T04:42:42.1571393Z <---
2016-06-16T04:42:42.1571393Z ---> (Inner Exception #2) System.Management.Automation.RemoteException: Error count: 1.
2016-06-16T04:42:42.1571393Z <---
2016-06-16T04:42:42.1727397Z ---> (Inner Exception #3) System.Management.Automation.RuntimeException: Info: Updating file (projectnameWeb\bin\Antlr3.Runtime.dll). ---> System.Management.Automation.RuntimeException: Info: Updating file (projectnameWeb\bin\Antlr3.Runtime.dll).
2016-06-16T04:42:42.1727397Z    --- End of inner exception stack trace ---
2016-06-16T04:42:42.1727397Z    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2016-06-16T04:42:42.1727397Z    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2016-06-16T04:42:42.1727397Z    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2016-06-16T04:42:42.1727397Z    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2016-06-16T04:42:42.1727397Z    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2016-06-16T04:42:42.1727397Z    at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
2016-06-16T04:42:42.1727397Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.<>c__DisplayClass28_0.<Invoke>b__0()
2016-06-16T04:42:42.1727397Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.<>c__DisplayClass19_0`1.<Execute>b__0()
2016-06-16T04:42:42.1727397Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute(Action action)
2016-06-16T04:42:42.1727397Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Utilities.RetryExecutor.Execute[T](Func`1 action)
2016-06-16T04:42:42.1727397Z    at Microsoft.VisualStudio.Services.DevTestLabs.RemoteDeployer.Deployment.PowershellExecutor.Invoke(String errorContextMessage, Boolean writeResultToLog, Boolean isCancellable, ActionPreference errorActionPreference)<---
2016-06-16T04:42:42.1727397Z Entering script MsDeployOnTargetMachines.ps1
2016-06-16T04:42:42.1727397Z Entering Execute-Main function
2016-06-16T04:42:42.1727397Z WebDeployPackage = C:\projectname\Publish\WebsiteName.WEB.zip
2016-06-16T04:42:42.1727397Z WebDeployParamFile = 
2016-06-16T04:42:42.1727397Z OverRideParams = name="IIS Web Application Name",value="projectnameWeb"
2016-06-16T04:42:42.1727397Z Deploying website. Running command: "C:\Program Files\IIS\Microsoft Web Deploy V3\msDeploy.exe"  -verb:sync -source:package="C:\projectname\Publish\WebsiteName.WEB.zip"  -setParam:name="IIS Web Application Name",value="projectnameWeb" -dest:auto -retryAttempts:3 -retryInterval:3000
2016-06-16T04:42:42.1727397Z Deployment failed on machine projectname-dev.myazureregion.cloudapp.azure.com with following message : System.Exception: Error Code: ERROR_FILE_IN_USE
2016-06-16T04:42:42.1883401Z ##[error]Microsoft.PowerShell.Commands.WriteErrorException: Deployment on one or more machines failed.
2016-06-16T04:42:42.1883401Z ##[error]For more info please refer to http://aka.ms/iisextnreadme)

**Comment by mvvsubbu** [comment]
This error is coming while deploying website, We have a user to add take app offline feature we will update with that feature soon. For now you can modify the following line in MsDeployOnTargetMachines.ps1 file of IISWebDeploy Task and increase the patch number of the task and upload to your TFS account.

Actual:
$msDeployCmdArgs = [string]::Format(' -verb:sync -source:package="{0}" {1} -dest:auto -retryAttempts:3 -retryInterval:3000', $webDeployPackage, $msDeployCmdArgs)

Modified:

$msDeployCmdArgs = [string]::Format(' -verb:sync -source:package="{0}" {1} -dest:auto -retryAttempts:3 -retryInterval:3000  **-enableRule:AppOffline'**, $webDeployPackage, $msDeployCmdArgs)

**Comment by AHoran** [comment]
Your change seems to have worked. I've completed 2 deployments now. Thanks

I did also test a suggestion from elsewhere to add
`  <EnableMSDeployAppOffline>True</EnableMSDeployAppOffline>`

to my .pubxml file, which didn't work.

**Comment by mvvsubbu** [comment]
Ok thanks for confirming I am closing the issue.

**Comment by AHoran** [comment]
I do still hit the problem occasionally, but it is much reduced. Unfortunately I've not captured the logs on those occasions in order to check if it's the same file.

**Comment by mvvsubbu** [comment]
This particular option brings the website down before deployment and hence no files should be in use thus file in use error should not happen. If it is still happening means either msdeploy is not doing the right thing or some file handles are not release completely before the deployment is started. Can you give idea on frequency (%age failure).

**Comment by AHoran** [comment]
It might be 1 in 10 or 1 in 20. Once it starts happening though that site is left in a 'Site Maintenance' state, and even when you redeploy the file remains in use. Only reboot or IISReset fixes the problem.
I have re-enabled the debug log and will wait for a recurrence.

**Comment by mvvsubbu** [comment]
If you know the dll name there are other options that you can set, but this options will skip deploying that dll
-skip:objectName=filePath,absolutePath=" RobustHashWrapper.dll "

**Comment by AHoran** [comment]
Previously it was Antlr3.Runtime.dll. I have re-enabled the debug logging, and am waiting for the next failure.

**Comment by AHoran** [comment]
According to the detailed logs it's happening with the dll from our own project.

**Comment by AHoran** [comment]
Have just discovered that my web.config contains:

```
<system.web>
    <hostingEnvironment shadowCopyBinAssemblies="false" />
```

I suspect that this might be why i'm suffering the problem so frequently. I'm currently uncertain why this is in my web.config, and will try and find out!
